### PR TITLE
36 merge swept oaes

### PR DESCRIPTION
**Pull request by hausersn1**
individual files (WB MEMR, swept DP, swept SF, teoae, FPL probe, and FPL ear) working on NEL1 and NEL2.

### CODE REVIEW

**Review by VarshaMAthreya — APPROVED** [review]

**Review by HeinzLabPurdue — CHANGES_REQUESTED** [review]
Remove the .icloud files.

**Review by sivaprakasaman — APPROVED** [review]
Conditional approve, once .icloud files are removed

**Review by hausersn1 — COMMENTED** [review]
okay i deleted them.

**Comment by sivaprakasaman** [comment]
> Remove the .icloud files.

okay done

**Review by HeinzLabPurdue — APPROVED** [review]

**Pull request merged**
