### PR TITLE
66 quantify nel delays

### PR DESCRIPTION
**Pull request by hausersn1**
Checked on NEL1 and NEL2. All working (confirmed in infinite tube, code will be checked for chin this week, but should work)
Still need to calculate ABR delays and add this to the measures themselves.

### CODE REVIEW

**Review by sivaprakasaman — APPROVED** [review]
Again, looks good to me. Final checks will be done next week, but shouldn't conflict with anything crazy. 

Was tested on NEL1 and NEL2

**Review by sivaprakasaman — APPROVED** [review]
MH supervised these changes. Still a bit iffy on the post-filter latency calculation...but functional and certainly better than not calculating anything at all.

**Review by sivaprakasaman — APPROVED** [review]
I saw a latency calculation with my own eyes.

**Review by HeinzLabPurdue — APPROVED** [review]
MH was here and helped check

**Pull request merged**
