### PR TITLE
AF Fiz the error when running AEP without calib, Also fixed the error…

### PR DESCRIPTION
**Pull request by Afaghfarhadi2**
fixed two issues with calib:

1- no calib error
2-runing calib after FPL calib

### CODE REVIEW

**Review by HeinzLabPurdue — APPROVED** [review]
This looks good to me - AS (I am Heinz Lab)

Pending verification on NEL2. Should prevent a calib-related spiral in AEP stuff and also prevent order-related calibrate.m issues (i.e. FPL calib being read as a valid calib file by the inv calib script).

**Review by HeinzLabPurdue — CHANGES_REQUESTED** [review]
Sorry, needs to exit gracefully second time!

**Review by sivaprakasaman — APPROVED** [review]
Now exits gracefully. Tested with AF on NEL 2.

**Review by HeinzLabPurdue — APPROVED** [review]
I approve. The error checking here should be correct now

**Pull request merged**
